import React from 'react';
import { ArrowRight, BarChart3, Target, Zap, Activity } from 'lucide-react';
import { AppView } from '../types';

interface HeroProps {
  onStart: () => void;
  onPmfTest?: () => void;
}

export const Hero: React.FC<HeroProps> = ({ onStart, onPmfTest }) => {
  return (
    <div className="min-h-screen flex flex-col justify-center items-center relative overflow-hidden bg-slate-900 text-white">
      {/* Background decoration */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden z-0">
        <div className="absolute top-[-10%] right-[-10%] w-[500px] h-[500px] bg-brand-500/10 rounded-full blur-[100px]"></div>
        <div className="absolute bottom-[-10%] left-[-10%] w-[500px] h-[500px] bg-indigo-500/10 rounded-full blur-[100px]"></div>
      </div>

      <div className="z-10 max-w-4xl px-6 text-center">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-800 border border-slate-700 text-brand-400 text-sm font-medium mb-6">
          <Zap size={16} />
          <span>AI-Powered Business Intelligence</span>
        </div>
        
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6 bg-gradient-to-r from-white via-slate-200 to-slate-400 bg-clip-text text-transparent">
          Decode Your <br />
          Growth Potential
        </h1>
        
        <p className="text-lg md:text-xl text-slate-400 mb-10 max-w-2xl mx-auto">
          Get a comprehensive diagnosis of your Strategy, Sales, and Operations in under 2 minutes. Receive a bespoke 30-day roadmap generated by our advanced AI.
        </p>

        <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
          <button 
            onClick={onStart}
            className="group relative px-8 py-4 bg-brand-600 hover:bg-brand-500 text-white font-semibold rounded-lg shadow-lg shadow-brand-500/20 transition-all duration-300 flex items-center gap-3 overflow-hidden"
          >
             <span className="relative z-10">Start Diagnostic</span>
             <ArrowRight className="relative z-10 group-hover:translate-x-1 transition-transform" />
             <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-700"></div>
          </button>
          
          {onPmfTest && (
            <button 
              onClick={onPmfTest}
              className="px-8 py-4 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-300 hover:text-white font-semibold rounded-lg transition-all flex items-center gap-2"
            >
               <Activity size={18} />
               <span>Check PMF Score</span>
            </button>
          )}
        </div>

        <div className="mt-16 grid grid-cols-1 md:grid-cols-3 gap-8 text-left">
          <Feature 
            icon={<BarChart3 className="text-blue-400" />}
            title="Data-Driven Score"
            desc="Quantify your business maturity across 4 key pillars."
          />
          <Feature 
            icon={<Target className="text-red-400" />}
            title="Gap Analysis"
            desc="Identify the exact bottlenecks slowing your revenue."
          />
          <Feature 
            icon={<Zap className="text-yellow-400" />}
            title="Action Plan"
            desc="Receive specific, prioritized tasks to fix issues today."
          />
        </div>
      </div>
    </div>
  );
};

const Feature = ({ icon, title, desc }: { icon: React.ReactNode, title: string, desc: string }) => (
  <div className="p-6 rounded-2xl bg-slate-800/50 border border-slate-700 backdrop-blur-sm hover:bg-slate-800 transition-colors">
    <div className="mb-4 p-3 bg-slate-900 rounded-lg w-fit border border-slate-700">
      {icon}
    </div>
    <h3 className="text-lg font-semibold text-white mb-2">{title}</h3>
    <p className="text-sm text-slate-400 leading-relaxed">{desc}</p>
  </div>
);